name: firebase_remote_helper
description: This plugin makes it easier for you to use firebase remote config.
version: 0.2.0
homepage: https://github.com/vnniz/firebase_remote_helper

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  firebase_remote_config: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
