name: firebase_remote_helper
description: This plugin will help you easier to use firebase remote config.
version: 0.0.1+2
homepage: https://github.com/vursin/firebase_remote_helper

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: