name: firebase_remote_helper
description: This plugin makes it easier for you to use firebase remote config.
version: 0.3.1
homepage: https://github.com/lamnhan066/firebase_remote_helper

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  firebase_remote_config: ^4.2.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
