name: firebase_remote_helper
description: This plugin makes it easier for you to use firebase remote config.
version: 0.6.0
homepage: https://github.com/lamnhan066/firebase_remote_helper

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

